version: "2"
linters:
  default: all
  enable:
    - errcheck
    - staticcheck
    - govet
    - bodyclose
run:
  relative-path-mode: cfg
  # Limits how many goroutines to use; defaults to num CPUs
  concurrency: 8
  # Stop lint if it's stalled—prevents hangs in large repos
  timeout: 5m
issues:
  # Skip linting generated files
  exclude-generated: true
linters-settings:
  cyclop:
    max-complexity: 15
    package-average: 1.0
  gocognit:
    min-complexity: 15
  dupl:
    threshold: 120
  funlen:
    lines: 200
    statements: 100
  prealloc:
    simple: true
    range-loops: false
    for-loops: true
  errcheck:
    check-type-assertions: true
  gocritic:
    enabled-checks: ["all"]
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - your/module/path
    gofmt:
      simplify: true
