return {
  "nvim-treesitter/nvim-treesitter",
  event = "VeryLazy",
  run = ":TSUpdate",
  ensure_installed = {
    "bash",
    "c",
    "cpp",
    "css",
    "dockerfile",
    "gitignore",
    "go",
    "gomod",
    "gosum",
    "html",
    "htmldjango",
    "javascript",
    "json",
    "jsonc",
    "lua",
    "markdown",
    "markdown_inline",
    "python",
    "regex",
    "rust",
    "sql",
    "svelte",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vue",
    "yaml",
  },
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  indent = { enable = true },
  autotag = { enable = true },
  context_commentstring = { enable = true },
}
